# UAE Aid Agency - embed_partner_logos.ps1
# Downloads official logos and embeds them as base64 in partner_logos.js
# Usage: powershell -ExecutionPolicy Bypass -File ".\tier2_alert_agent\embed_partner_logos.ps1"

$ErrorActionPreference = "Continue"
$here   = Split-Path -Parent $MyInvocation.MyCommand.Path
$parent = Split-Path -Parent $here
$outPath = Join-Path $parent "partner_logos.js"

$AGENCIES = [ordered]@{
    "WFP"        = @("https://cdn.wfp.org/brand/ui/v0.13.0/assets/logos/standard/png/wfp-logo-standard-blue-en.png","https://cdn.wfp.org/brand/ui/v0.12.0/assets/logos/standard/png/wfp-logo-standard-blue-en.png","https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/World-food-programme-wfp-logo.svg/200px-World-food-programme-wfp-logo.svg.png")
    "UNICEF"     = @("https://www.unicef.org/sites/default/files/styles/logo/public/UNICEF-Logo.png","https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Logo_of_UNICEF.svg/200px-Logo_of_UNICEF.svg.png")
    "UNHCR"      = @("https://www.unhcr.org/assets/img/logo.png","https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/UN_Refugee_Agency_Logo.svg/200px-UN_Refugee_Agency_Logo.svg.png")
    "WHO"        = @("https://www.who.int/images/default-source/infographics/who-emblem.png","https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/World_Health_Organization_Logo.svg/200px-World_Health_Organization_Logo.svg.png")
    "OCHA"       = @("https://www.unocha.org/sites/default/files/OCHA-logo-blue.png","https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/United_Nations_Office_for_the_Coordination_of_Humanitarian_Affairs_Logo.svg/200px-United_Nations_Office_for_the_Coordination_of_Humanitarian_Affairs_Logo.svg.png")
    "FAO"        = @("https://www.fao.org/images/corporatelibraryimages/fao-logo-en.svg","https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/FAO_logo.svg/200px-FAO_logo.svg.png")
    "ICRC"       = @("https://www.icrc.org/themes/custom/icrc_theme/logo.svg","https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/ICRC_logo.svg/200px-ICRC_logo.svg.png")
    "UNRWA"      = @("https://www.unrwa.org/sites/default/files/unrwa_logo_0.png","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/UNRWA_emblem.svg/200px-UNRWA_emblem.svg.png")
    "IOM"        = @("https://www.iom.int/themes/iom_theme/logo/iom_logo.png","https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/IOM_logo.svg/200px-IOM_logo.svg.png")
    "IFRC"       = @("https://www.ifrc.org/sites/default/files/2021-06/IFRC-logo.png","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/IFRC_logo.svg/200px-IFRC_logo.svg.png")
    "World Bank" = @("https://www.worldbank.org/content/dam/wbr/logo/logo-wb-header-en.svg","https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/The_World_Bank_logo.svg/200px-The_World_Bank_logo.svg.png")
    "IMF"        = @("https://www.imf.org/-/media/Images/IMF/imf-logo-eng-blk.ashx","https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/IMF_logo.svg/200px-IMF_logo.svg.png")
    "UAERCA"     = @("https://www.rcuae.ae/Content/images/logo.png","https://www.rcuae.ae/images/logo.png")
    "KSRELIEF"   = @("https://ksrelief.org/Images/logo.png","https://ksrelief.org/assets/images/logo.png")
}

function TryDownload($urls) {
    foreach ($url in $urls) {
        try {
            $wc = New-Object System.Net.WebClient
            $wc.Headers.Add("User-Agent","Mozilla/5.0 (Windows NT 10.0; Win64; x64)")
            $bytes = $wc.DownloadData($url)
            if ($bytes -and $bytes.Length -gt 500) {
                if ($url -match '\.svg') { $mime = "image/svg+xml" }
                elseif ($url -match '\.jpg|\.jpeg') { $mime = "image/jpeg" }
                else { $mime = "image/png" }
                $b64 = [Convert]::ToBase64String($bytes)
                return "data:$mime;base64,$b64"
            }
        } catch { }
    }
    return $null
}

Write-Host ""
Write-Host "Downloading partner logos..." -ForegroundColor Cyan
$results = [ordered]@{}

foreach ($key in $AGENCIES.Keys) {
    $pad = $key.PadRight(14)
    Write-Host -NoNewline "  $pad : "
    $uri = TryDownload $AGENCIES[$key]
    if ($uri) {
        $kb = [int]($uri.Length / 1024)
        $results[$key] = $uri
        Write-Host "OK  ($kb KB)" -ForegroundColor Green
    } else {
        Write-Host "FAILED - will use fallback emblem" -ForegroundColor Yellow
    }
}

Write-Host ""

# Write JS file
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// UAE Aid Agency - Partner Logos")
[void]$sb.AppendLine("// Auto-generated by tier2_alert_agent/embed_partner_logos.ps1")
[void]$sb.AppendLine("// Re-run to refresh. Loaded by dashboard at startup.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("window.PARTNER_LOGOS = {")
foreach ($key in $results.Keys) {
    $escaped = $key -replace '"','\"'
    [void]$sb.AppendLine("  `"$escaped`": `"$($results[$key])`",")
}
[void]$sb.AppendLine("};")

[IO.File]::WriteAllText($outPath, $sb.ToString(), [Text.UTF8Encoding]::new($false))

$sizeKb = [int]((Get-Item $outPath).Length / 1024)
Write-Host "Done: $($results.Count) logos -> partner_logos.js ($sizeKb KB)" -ForegroundColor Green
Write-Host "Hard-refresh the dashboard (Ctrl+Shift+R) to see logos." -ForegroundColor Cyan
Write-Host ""
